name: UHC
author: Centralis
version: 1.0
main: com.iangongwer.main.Main

commands:
  whitelist:
    permission: uhc.staff
    aliases: [wl]
  practice:
    aliases: [prac, p]
  broadcast:
    permission: uhc.staff
  mute:
    permission: uhc.staff
  start:
    permission: uhc.staff
  mutechat:
    permission: uhc.staff
  calculate:
    permission: uhc.staff
  scenario:
    aliases: [scen, scenarios]
  staff:
    permission: uhc.staff
  latescatter:
    aliases: [ls]
  team:
    aliases: [t, teams]
  teamchat:
  teamcoords:
    aliases: [tl, sendcoords, pmcoords, teamloc]
  respawn:
    permission: uhc.staff
  stats:
    aliases: [stat]
  database:
    permission: uhc.staff
    aliases: [db]
  banplayer:
    permission: uhc.staff
  unbanplayer:
    permission: uhc.staff
  discord:
    aliases: [disc]
  killtop:
    aliases: [killstop, kt, leaderboard, lb]
  recipes:
    aliases: [craft, crafts, crafting, recipe]
  heal:
    permission: uhc.staff
  schedule:
    permission: uhc.staff
  helpop:
    aliases: [help, ask, assist, assistance]
  uhc:
    aliases: [config, conf, rules]
    
depend: [Netherboard]